### ISSUE TITLE
Missing Module:  'MinkowskiEngineBackend._C' has no attribute 'CoordinateMapManagerGPU_c10'

### ISSUE THREAD

**Issue by wboschmann** [chrischoy/FCGF#47]
Hello Chris,

by trying to run FCGF in a docker and face some error that i cant solve.

I am using the following script to build the container:

<details>
  <summary>dockerfile</summary>

```

FROM nvidia/cuda:10.2-devel

RUN apt update \
    && apt install -y python3.7 python3-pip git \
    && python3.7 -m pip install --upgrade --force pip

# Required by ME
RUN apt install -y libopenblas-dev python3.7-dev

# ME installation requires this.
# Basicly just to use pip instead of pip3 ?
RUN ln -s /usr/bin/python3.7 /usr/bin/python && ln -s /usr/bin/pip3 /usr/bin/pip

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN apt-get install -y\
      build-essential \
      apt-utils \
      ca-certificates \
      wget \
      git \
      vim \
      libssl-dev \
      curl \
      unzip \
      unrar

# Torch versions: https://pytorch.org/get-started/previous-versions/
RUN python3.7 -m pip install torch==1.5.1 torchvision==0.6.1
RUN export CXX=g++-7
RUN pip install git+https://github.com/NVIDIA/MinkowskiEngine.git@v0.5  

RUN apt-get install -y libsm6 libxrender1 libfontconfig1 libpython3.7-dev libopenblas-dev
RUN apt install libgl1-mesa-glx -y

WORKDIR /app
# Avoid adding files by copy or add -> changes need new docker build
# use volumes 
# only for intsallation purpose:
COPY ./FCGF/requirements.txt /tmp/FCGF/requirements.txt 
RUN python3.7 -m pip install -r /tmp/FCGF/requirements.txt

CMD [ "/bin/bash", "" ]
```
  
</details>
 
and run it with the following script:

<details>
  <summary>container build/run</summary>

```
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

docker build -t mke_docker:0.5 .

docker rm -f mke0

docker run --privileged -it \
    -v /media/wboschmann/Work-Drive2/SRS-WORK/Data/:/app/Data \
    -v $SCRIPTPATH/FCGF:/app/FCGF \
    --name mke0 \
    --gpus all \
    --entrypoint /bin/bash \
    mke_docker:0.5
```

</details>

I tested by running the train skript for threedmatch and run into the following error

<details>
  <summary>output</summary>

```
root@743a96027975:/app/FCGF# python train.py --threed_match_dir /app/Data/threedmatch/
12/17 18:07:00 ===> Configurations
12/17 18:07:00     out_dir: outputs
12/17 18:07:00     trainer: HardestContrastiveLossTrainer
12/17 18:07:00     save_freq_epoch: 1
12/17 18:07:00     batch_size: 4
12/17 18:07:00     val_batch_size: 1
12/17 18:07:00     use_hard_negative: True
12/17 18:07:00     hard_negative_sample_ratio: 0.05
12/17 18:07:00     hard_negative_max_num: 3000
12/17 18:07:00     num_pos_per_batch: 1024
12/17 18:07:00     num_hn_samples_per_batch: 256
12/17 18:07:00     neg_thresh: 1.4
12/17 18:07:00     pos_thresh: 0.1
12/17 18:07:00     neg_weight: 1
12/17 18:07:00     use_random_scale: False
12/17 18:07:00     min_scale: 0.8
12/17 18:07:00     max_scale: 1.2
12/17 18:07:00     use_random_rotation: True
12/17 18:07:00     rotation_range: 360
12/17 18:07:00     train_phase: train
12/17 18:07:00     val_phase: val
12/17 18:07:00     test_phase: test
12/17 18:07:00     stat_freq: 40
12/17 18:07:00     test_valid: True
12/17 18:07:00     val_max_iter: 400
12/17 18:07:00     val_epoch_freq: 1
12/17 18:07:00     positive_pair_search_voxel_size_multiplier: 1.5
12/17 18:07:00     hit_ratio_thresh: 0.1
12/17 18:07:00     triplet_num_pos: 256
12/17 18:07:00     triplet_num_hn: 512
12/17 18:07:00     triplet_num_rand: 1024
12/17 18:07:00     model: ResUNetBN2C
12/17 18:07:00     model_n_out: 32
12/17 18:07:00     conv1_kernel_size: 5
12/17 18:07:00     normalize_feature: True
12/17 18:07:00     dist_type: L2
12/17 18:07:00     best_val_metric: feat_match_ratio
12/17 18:07:00     optimizer: SGD
12/17 18:07:00     max_epoch: 100
12/17 18:07:00     lr: 0.1
12/17 18:07:00     momentum: 0.8
12/17 18:07:00     sgd_momentum: 0.9
12/17 18:07:00     sgd_dampening: 0.1
12/17 18:07:00     adam_beta1: 0.9
12/17 18:07:00     adam_beta2: 0.999
12/17 18:07:00     weight_decay: 0.0001
12/17 18:07:00     iter_size: 1
12/17 18:07:00     bn_momentum: 0.05
12/17 18:07:00     exp_gamma: 0.99
12/17 18:07:00     scheduler: ExpLR
12/17 18:07:00     icp_cache_path: /home/chrischoy/datasets/FCGF/kitti/icp/
12/17 18:07:00     use_gpu: True
12/17 18:07:00     weights: None
12/17 18:07:00     weights_dir: None
12/17 18:07:00     resume: None
12/17 18:07:00     resume_dir: None
12/17 18:07:00     train_num_thread: 2
12/17 18:07:00     val_num_thread: 1
12/17 18:07:00     test_num_thread: 2
12/17 18:07:00     fast_validation: False
12/17 18:07:00     nn_max_n: 500
12/17 18:07:00     dataset: ThreeDMatchPairDataset
12/17 18:07:00     voxel_size: 0.025
12/17 18:07:00     threed_match_dir: /app/Data/threedmatch/
12/17 18:07:00     kitti_root: /home/chrischoy/datasets/FCGF/kitti/
12/17 18:07:00     kitti_max_time_diff: 3
12/17 18:07:00     kitti_date: 2011_09_26
12/17 18:07:00 Loading the subset train from /app/Data/threedmatch/
12/17 18:07:00 Loading the subset val from /app/Data/threedmatch/
12/17 18:07:00 ResUNetBN2C(
  (conv1): MinkowskiConvolution(in=1, out=32, region_type=RegionType.HYPER_CUBE, kernel_size=[5, 5, 5], stride=[1, 1, 1], dilation=[1, 1, 1])
  (norm1): MinkowskiBatchNorm(32, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block1): BasicBlockBN(
    (conv1): MinkowskiConvolution(in=32, out=32, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(32, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=32, out=32, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(32, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv2): MinkowskiConvolution(in=32, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm2): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block2): BasicBlockBN(
    (conv1): MinkowskiConvolution(in=64, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=64, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv3): MinkowskiConvolution(in=64, out=128, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm3): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block3): BasicBlockBN(
    (conv1): MinkowskiConvolution(in=128, out=128, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=128, out=128, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv4): MinkowskiConvolution(in=128, out=256, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm4): MinkowskiBatchNorm(256, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block4): BasicBlockBN(
    (conv1): MinkowskiConvolution(in=256, out=256, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(256, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=256, out=256, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(256, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv4_tr): MinkowskiConvolutionTranspose(in=256, out=128, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm4_tr): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block4_tr): BasicBlockBN(
    (conv1): MinkowskiConvolution(in=128, out=128, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=128, out=128, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv3_tr): MinkowskiConvolutionTranspose(in=256, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm3_tr): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block3_tr): BasicBlockBN(
    (conv1): MinkowskiConvolution(in=64, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=64, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv2_tr): MinkowskiConvolutionTranspose(in=128, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm2_tr): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block2_tr): BasicBlockBN(
    (conv1): MinkowskiConvolution(in=64, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=64, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv1_tr): MinkowskiConvolution(in=96, out=64, region_type=RegionType.HYPER_CUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
  (final): MinkowskiConvolution(in=64, out=32, region_type=RegionType.HYPER_CUBE, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
)
12/17 18:07:02 Resetting the data loader seed to 0
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main(config)
  File "train.py", line 63, in main
    trainer.train()
  File "/app/FCGF/lib/trainer.py", line 124, in train
    val_dict = self._valid_epoch()
  File "/app/FCGF/lib/trainer.py", line 321, in _valid_epoch
    coordinates=input_dict['sinput0_C'].to(self.device))
  File "/usr/local/lib/python3.7/dist-packages/MinkowskiEngine/MinkowskiTensor.py", line 327, in __init__
    minkowski_algorithm=minkowski_algorithm,
  File "/usr/local/lib/python3.7/dist-packages/MinkowskiEngine/MinkowskiCoordinateManager.py", line 142, in __init__
    self._CoordinateManagerClass = getattr(_C, "CoordinateMapManager" + postfix)
AttributeError: module 'MinkowskiEngineBackend._C' has no attribute 'CoordinateMapManagerGPU_c10'
```
</details>

On the fist view everything seems fine, the systems seems to have cuda support and the required packeges seem to be available

<details>
  <summary>pip list</summary>

```
root@743a96027975:/app/FCGF# pip list
Package             Version
------------------- --------
argon2-cffi         20.1.0
asn1crypto          0.24.0
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
bleach              3.2.1
cffi                1.14.4
cryptography        2.1.4
cycler              0.10.0
decorator           4.4.2
defusedxml          0.6.0
easydict            1.9
entrypoints         0.3
future              0.18.2
future-fstrings     1.2.0
idna                2.6
importlib-metadata  3.3.0
ipykernel           5.4.2
ipython             7.19.0
ipython-genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.2
Jinja2              2.11.2
joblib              1.0.0
jsonschema          3.2.0
jupyter-client      6.1.7
jupyter-core        4.7.0
jupyterlab-pygments 0.1.2
keyring             10.6.0
keyrings.alt        3.0
kiwisolver          1.3.1
MarkupSafe          1.1.1
matplotlib          3.3.3
MinkowskiEngine     0.5.0rc0
mistune             0.8.4
nbclient            0.5.1
nbconvert           6.0.7
nbformat            5.0.8
nest-asyncio        1.4.3
notebook            6.1.5
numpy               1.19.4
open3d              0.9.0.0
packaging           20.8
pandocfilters       1.4.3
parso               0.7.1
pexpect             4.8.0
pickleshare         0.7.5
Pillow              8.0.1
pip                 20.3.2
prometheus-client   0.9.0
prompt-toolkit      3.0.8
protobuf            3.14.0
ptyprocess          0.6.0
pycparser           2.20
pycrypto            2.6.1
Pygments            2.7.3
pygobject           3.26.1
pyparsing           2.4.7
pyrsistent          0.17.3
python-dateutil     2.8.1
pyxdg               0.25
pyzmq               20.0.0
scikit-learn        0.23.2
scipy               1.5.4
SecretStorage       2.3.1
Send2Trash          1.5.0
setuptools          39.0.1
six                 1.11.0
tensorboardX        2.1
terminado           0.9.1
testpath            0.4.4
threadpoolctl       2.1.0
torch               1.5.1
torchvision         0.6.1
tornado             6.1
traitlets           5.0.5
typing-extensions   3.7.4.3
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.30.0
widgetsnbextension  3.5.1
zipp                3.4.0
```

</details>

Does anyone else face similar problems ?

I hope the problem is reproducable, if any futher information is requred just let me know.

Thanks in advance.

**Comment by AmnonDrory** [comment]
I have a similar problem. Any news?

**Comment by chrischoy** [comment]
This is due to the installation script not being able to access gpu and compiled a CPU only version.

**Comment by chrischoy** [comment]
https://github.com/NVIDIA/MinkowskiEngine/commit/c54f3cce14b117382fdf849a211168de078df9eb Now warn when using CUDA features without CUDA ME installation.
